export const CARGANDO_CATEGORIAS = 'CARGANDO_CATEGORIAS'
export const UPDATE_FAVORITES = 'UPDATE_FAVORITES'



export const ADD_FAVORITE_CATEGORY = 'ADD_FAVORITE_CATEGORY';
export const REMOVE_FAVORITE_CATEGORY = 'REMOVE_FAVORITE_CATEGORY';

export const HEART_ADD = 'HEART_ADD';
export const HEART_REMOVE = 'HEART_REMOVE';